export const CHANGE_TOP_BANNERS = "CHANGE_TOP_BANNERS";

export const CHANGE_HOT_RECOMMENDS = "CHANGE_HOT_RECOMMENDS";

export const CHANGE_SETTLE_SINGERS = "CHANGE_SETTLE_SINGERS";

export const CHANGE_NEW_ALBUMS = "CHANGE_NEW_ALBUM";
