export const CHANGE_TOP_BANNERS = "CHANGE_TOP_BANNERS";

export const CHANGE_HOT_RECOMMENDS = "CHANGE_HOT_RECOMMENDS";

export const CHANGE_SETTLE_SINGERS = "CHANGE_SETTLE_SINGERS";

export const CHANGE_NEW_ALBUMS = "CHANGE_NEW_ALBUM";

export const CHANGE_DJ_TOP_LIST = "CHANGE_DJ_TOP_LIST";

export const CHANGE_UP_RANKING = "CHANGE_UP_RANKING";

export const CHANGE_NEW_RANKING = "CHANGE_NEW_RANKING";

export const CHANGE_ORIGIN_RANKING = "CHANGE_ORIGIN_RANKING";
